model_provider = "crs"
model = "gpt-5.3-codex"
model_reasoning_effort = "xhigh"

disable_response_storage = true
preferred_auth_method = "apikey"

[model_providers.crs]
name = "crs"
base_url = "http://api.drlj.cn/openai"
wire_api = "responses"
requires_openai_auth = true
env_key = "cr_84471ef92d4bf8271b995fd5722b5376952962746e783cc3a711989e4776d0a3"